### ISSUE TITLE
how ratings will be bound by 0 and 5

### ISSUE THREAD

**Issue by tarun1820** [twolodzko/sgdmf#1]
consider matrix factorisation on data having ratings from 0 and 5 . is it quarentee that mf will bound by 0 and 5

**Comment by twolodzko** [comment]
Hi,

It's described in greater detail in the paper mentioned in README. But to answer your question, it's a simple, linear model that gives no guarantees to predict the bounded ratings. However predicting the ratings is not the point of the model, the main point is making recommendations, it was designed for this purpose. Also, remember that this is an old code, not a production quality.
